
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-urlgz
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: urlgz
      MARIADB_USER: user
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - urlgz-net


networks:
  urlgz-net:
    driver: bridge

