spring:
  application:
    name: urlgz

  logging:
    level:
      br.com.urlgz: DEBUG

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/urlgz
    username: user
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      logging.level.org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  version: 1.0.0
  info:
    title: URLGZ
    description: API encurtadora de url
    version: v1
