spring:
  application:
    name: urlgz
    
  datasource:
    driver: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/urglgz 
    username: user
    password: root
  jpa:
    hibernate:
      format_sql: true   
      use_sql_comments: true
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  
